<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-VSBTU4D1" failures="1" tests="3" name="configurePIM.TestRunnerConfigurePIM" time="99.376" errors="0" timestamp="2020-12-24T10:48:20 IST" skipped="0">
  <testcase classname="configurePIM.TestRunnerConfigurePIM" name="runScenario" time="30.580"/>
  <system-out/>
  <testcase classname="configurePIM.TestRunnerConfigurePIM" name="runScenario" time="29.195">
    <failure message="When user does not select any checkbox to save, still shows successful message on click" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: When user does not select any checkbox to save, still shows successful message on click
at org.junit.Assert.fail(Assert.java:89)
at configurePIM.StepDefConfigurePIM.error_message_is_displayed_or_user_is_prompted_that_no_field_is_chosen(StepDefConfigurePIM.java:155)
at âœ½.error message is displayed or user is prompted that no field is chosen(classpath:configurePIM/configurePIM.feature:32)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="configurePIM.TestRunnerConfigurePIM" name="runScenario" time="39.601"/>
  <system-out/>
</testsuite> <!-- configurePIM.TestRunnerConfigurePIM -->
